### ISSUE TITLE
Using lib in Service

### ISSUE THREAD

**Issue by AlirezaAkbarix** [mcharmas/Android-ReactiveLocation#111]
I have a service that gets location in background. This is my service code:

 `public class MainLocationService extends Service {
    Subscription locationSubscription;

```
@Nullable
@Override
public IBinder onBind(Intent intent) {
    return null;
}

@Override
public int onStartCommand(Intent intent, int flags, int startId) {
    LocationRequest request = new LocationRequest().setPriority(LocationRequest.PRIORITY_HIGH_ACCURACY)
        .setNumUpdates(10)
        .setInterval(1000);

    ReactiveLocationProvider locationProvider = new ReactiveLocationProvider(getApplicationContext());
    locationSubscription = locationProvider.getUpdatedLocation(request)
        .map(location -> {
            SimpleDateFormat format = new SimpleDateFormat("mm:ss");
            return format.format(new Date()) + ": " + location.getLongitude() + "|||" + location.getLatitude();
        }).subscribe(s -> new AlertDialog.Builder(getApplicationContext()).setMessage(s).show());
    return super.onStartCommand(intent, flags, startId);
}

@Override
public void onDestroy() {
    super.onDestroy();
    if (locationSubscription != null)
        locationSubscription.unsubscribe();
}
```

}
`

When the lib finds location, the app crashes with this error log:
`FATAL EXCEPTION: main
                                                                         Process: com.akbari.rxworkspace2, PID: 20668
                                                                         rx.exceptions.OnErrorNotImplementedException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                             at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(Unknown)
                                                                             at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(Unknown)
                                                                             at rx.internal.util.ActionSubscriber.onError(Unknown)
                                                                             at rx.observers.SafeSubscriber._onError(Unknown)
                                                                             at rx.observers.SafeSubscriber.onError(Unknown)
                                                                             at rx.exceptions.Exceptions.throwOrReport(Unknown)
                                                                             at rx.observers.SafeSubscriber.onNext(Unknown)
                                                                             at rx.internal.operators.OperatorMap$MapSubscriber.onNext(Unknown)
                                                                             at pl.charmas.android.reactivelocation.observables.location.LocationUpdatesObservable$1.onLocationChanged(Unknown)
                                                                             at com.google.android.gms.location.internal.zzk$zzb.handleMessage(Unknown)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:145)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5938)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
                                                                          Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                             at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(Unknown)
                                                                             at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(Unknown)
                                                                             at android.support.v7.app.AppCompatDelegateImplV7.setContentView(Unknown)
                                                                             at android.support.v7.app.AppCompatDialog.setContentView(Unknown)
                                                                             at android.support.v7.app.AlertController.installContent(Unknown)
                                                                             at android.support.v7.app.AlertDialog.onCreate(Unknown)
                                                                             at android.app.Dialog.dispatchOnCreate(Dialog.java:463)
                                                                             at android.app.Dialog.show(Dialog.java:288)
                                                                             at android.support.v7.app.AlertDialog$Builder.show(Unknown)
                                                                             at com.akbari.rxworkspace2.MainLocationService$-int_onStartCommand_android_content_Intent_intent_int_flags_int_startId_LambdaImpl1.call(MainLocationService.java:50)
                                                                             at rx.internal.util.ActionSubscriber.onNext(Unknown)
                                                                             at rx.observers.SafeSubscriber.onNext(Unknown) 
                                                                             at rx.internal.operators.OperatorMap$MapSubscriber.onNext(Unknown) 
                                                                             at pl.charmas.android.reactivelocation.observables.location.LocationUpdatesObservable$1.onLocationChanged(Unknown) 
                                                                             at com.google.android.gms.location.internal.zzk$zzb.handleMessage(Unknown) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:145) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5938) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195) `

If I don't use `Service` and show the found location in `Activity` everything is OK, but when I use `Service` and device finds location it crashs! also it's clear that I use an `appcompat` theme.

**Comment by cyrixmorten** [comment]
Can you try to simply log the result of your subscription instead of building a Dialog?

I suspect the your app crashes because you build the Dialog outside of an Activity context. If my suspicion turns out to be true, the problem you have has nothing to do with this library.

Quick suggestion to alternatives if the dialog is important:
- Bind to the service in your main activity to communicate results to the activity and create the dialogs there
- Send broadcasts from the service which your activity picks up to create dialogs
- Create a wrapper activity, e.g. DialogActivity with a transparent background that creates a dialog. Then you can start that activity from the service (as starting new activities is allowed from application context)

**Comment by AlirezaAkbarix** [comment]
That's true! thanks!

**Comment by cyrixmorten** [comment]
You are welcome :)
