### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by Philio** [mcharmas/Android-ReactiveLocation#123]
I had this exception logged by Crashlytics:

    Fatal Exception: pl.charmas.android.reactivelocation.observables.GoogleAPIConnectionSuspendedException
        at pl.charmas.android.reactivelocation.observables.BaseObservable$ApiClientConnectionCallbacks.onConnectionSuspended(BaseObservable.java:102)
        at com.google.android.gms.internal.zzqd.zzd(Unknown Source:19000)
        at com.google.android.gms.internal.zzqa.begin(Unknown Source)
        at com.google.android.gms.internal.zzqf.zzd(Unknown Source)
        at com.google.android.gms.internal.zzpu.onConnected(Unknown Source)
        at com.google.android.gms.common.internal.zzk$1.onConnected$79e5e33f(Unknown Source)
        at com.google.android.gms.common.internal.zzd$zzd.handleMessage(Unknown Source)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5461)
        at java.lang.reflect.Method.invoke(Method.java)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by jemmyphan** [comment]
@Philio may i know why u closed this issue, or have you found the cause or solution?

**Comment by hugosvent** [comment]
@Philio anyone know how to solve this issue? this exception occured on my apps too.

**Comment by mcharmas** [comment]
This exception is thrown when connection to GMS is suspended. You can find details here: https://developers.google.com/android/reference/com/google/android/gms/common/api/GoogleApiClient.ConnectionCallbacks.html#onConnectionSuspended(int)

**Comment by Philio** [comment]
@jemmyphan I think I closed it as it was an implementation issue and not a problem with the library. Don't think it related to proguard.
