### ISSUE TITLE
App crashes while running places sample code

### ISSUE THREAD

**Issue by LOG-TAG** [mcharmas/Android-ReactiveLocation#135]
Crash report:

```
Process: pl.charmas.android.reactivelocation.sample, PID: 21898
                                                                                            rx.exceptions.OnErrorNotImplementedException
                                                                                                at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
                                                                                                at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
                                                                                                at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
                                                                                                at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:152)
                                                                                                at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
                                                                                                at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:216)
                                                                                                at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
                                                                                                at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:398)
                                                                                                at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:358)
                                                                                                at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:849)
                                                                                                at pl.charmas.android.reactivelocation.observables.PendingResultObservable$1.onResult(PendingResultObservable.java:25)
                                                                                                at com.google.android.gms.internal.zzpo$zza.zzb(Unknown Source)
                                                                                                at com.google.android.gms.internal.zzpo$zza.handleMessage(Unknown Source)
                                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                at android.os.Looper.loop(Looper.java:135)
                                                                                                at android.app.ActivityThread.main(ActivityThread.java:5292)
                                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                                at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
                                                                                             Caused by: java.lang.IllegalStateException
                                                                                                at com.google.android.gms.common.internal.zzab.zzbn(Unknown Source)
                                                                                                at com.google.android.gms.common.data.zzc.zzfq(Unknown Source)
                                                                                                at com.google.android.gms.common.data.zzc.<init>(Unknown Source)
                                                                                                at com.google.android.gms.location.places.internal.zzt.<init>(Unknown Source)
                                                                                                at com.google.android.gms.location.places.internal.zzn.<init>(Unknown Source)
                                                                                                at com.google.android.gms.location.places.PlaceLikelihoodBuffer.get(Unknown Source)
                                                                                                at pl.charmas.android.reactivelocation.sample.PlacesActivity$2.call(PlacesActivity.java:68)
                                                                                                at pl.charmas.android.reactivelocation.sample.PlacesActivity$2.call(PlacesActivity.java:65)
                                                                                                at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
                                                                                                at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
                                                                                                at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:398) 
                                                                                                at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:358) 
                                                                                                at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:849) 
                                                                                                at pl.charmas.android.reactivelocation.observables.PendingResultObservable$1.onResult(PendingResultObservable.java:25) 
                                                                                                at com.google.android.gms.internal.zzpo$zza.zzb(Unknown Source) 
                                                                                                at com.google.android.gms.internal.zzpo$zza.handleMessage(Unknown Source) 
                                                                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                                at android.os.Looper.loop(Looper.java:135) 
                                                                                                at android.app.ActivityThread.main(ActivityThread.java:5292) 
                                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
                                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699) 
```

**Comment by mcharmas** [comment]
You have to implement error callback in subscribe method. Exactly as exception says.
