### ISSUE TITLE
proguard

### ISSUE THREAD

**Issue by sytolk** [mcharmas/Android-ReactiveLocation#15]
I have use it with proguard and have this exception from Acra (I cant repeat it).
HUAWEI Y220-U00 Android '2.3.6
Is there some custom proguard configuration or RxJava ?

b.a.e: Error connecting to LocationClient.
        at b.a$2.a(Observable.java:5890)
        at b.c.a.b(SafeSubscriber.java:125)
        at b.c.a.a(SafeSubscriber.java:94)
        at b.d.a$1.a(OperatorFilter.java:47)
        at a.a.a.a.a.b.a(BaseLocationObservable.java:84)
        at com.google.android.gms.internal.cz.a(Unknown Source)
        at com.google.android.gms.internal.db.a(Unknown Source)
        at com.google.android.gms.internal.da.a(Unknown Source)
        at com.google.android.gms.internal.da.a(Unknown Source)
        at com.google.android.gms.internal.cv.b(Unknown Source)
        at com.google.android.gms.internal.cu.handleMessage(Unknown Source)
        at android.os.Handler.dispatchMessage(Handler.java:130)
        at android.os.Looper.loop(Looper.java:384)
        at android.app.ActivityThread.main(ActivityThread.java:3975)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:538)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:978)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:732)
        at dalvik.system.NativeStart.main(Native Method)
Caused by: a.a.a.a.a.c: Error connecting to LocationClient.
        ... 15 more
a.a.a.a.a.c: Error connecting to LocationClient.
        at a.a.a.a.a.b.a(BaseLocationObservable.java:84)
        at com.google.android.gms.internal.cz.a(Unknown Source)
        at com.google.android.gms.internal.db.a(Unknown Source)
        at com.google.android.gms.internal.da.a(Unknown Source)
        at com.google.android.gms.internal.da.a(Unknown Source)
        at com.google.android.gms.internal.cv.b(Unknown Source)
        at com.google.android.gms.internal.cu.handleMessage(Unknown Source)
        at android.os.Handler.dispatchMessage(Handler.java:130)
        at android.os.Looper.loop(Looper.java:384)
        at android.app.ActivityThread.main(ActivityThread.java:3975)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:538)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:978)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:732)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by cq321** [comment]
How to apply pro-guard upon reactive location library send me all details of pro-guard file of it

**Comment by sytolk** [comment]
You can test proguard-rx-java.pro from https://github.com/krschultz/android-proguard-snippets/pull/61
This is my maven proguard config I have use proguard snippets from https://github.com/krschultz/android-proguard-snippets
```xml
<plugin>
                <groupId>com.simpligility.maven.plugins</groupId>
                <artifactId>android-maven-plugin</artifactId>
                <version>4.3.0</version>
                <extensions>true</extensions>
                <configuration>
                    <proguard>
                        <skip>false</skip>
                        <configs>
                            <config>${env.ANDROID_HOME}/tools/proguard/proguard-android.txt</config>
                            <config>${project.basedir}/proguard.cfg</config>
                            <config>${project.basedir}/proguard-support-v7-appcompat.pro</config>
                            <config>${project.basedir}/proguard-google-play-services.pro</config>
                            <config>${project.basedir}/proguard-jackson-2.pro</config>
                            <config>${project.basedir}/proguard-rx-java.pro</config>
                            <config>${project.basedir}/proguard-acra.pro</config>
                        </configs>
                    </proguard>
                    <androidManifestFile>${project.basedir}/AndroidManifest.xml</androidManifestFile>
                    <assetsDirectory>${project.basedir}/assets</assetsDirectory>
                    <resourceDirectory>${project.basedir}/res</resourceDirectory>
                    <sdk>
                        <platform>${android-platform}</platform>
                    </sdk>
                    <emulator>
                        <avd>${android-emulator}</avd>
                    </emulator>
                    <undeployBeforeDeploy>true</undeployBeforeDeploy>
                    <extractDuplicates>true</extractDuplicates>
                </configuration>
            </plugin>
```

and this is my proguard.cfg
```
  -dump class_files.txt
  -printseeds seeds.txt
  -printusage unused.txt
  -printmapping mapping.txt
  -ignorewarnings
  -keepattributes Signature,EnclosingMethod

  -keep public class * extends android.app.Activity
  -keep public class * extends android.app.Application
  -keep public class * extends android.app.Service
  -keep public class * extends android.content.BroadcastReceiver
  -keep public class * extends android.content.ContentProvider
  -keep public class * extends android.app.backup.BackupAgentHelper
  -keep public class * extends android.preference.Preference
  -keep public class com.android.vending.licensing.ILicensingService
  -dontnote com.android.vending.licensing.ILicensingService


  # Preserve all native method names and the names of their classes.
  -keepclasseswithmembernames class * {
      native <methods>;
  }

  -keepclasseswithmembernames class * {
      public <init>(android.content.Context, android.util.AttributeSet);
  }

  -keepclasseswithmembernames class * {
      public <init>(android.content.Context, android.util.AttributeSet, int);
  }

 #### spring restTemplate
 -keep class * implements android.os.Parcelable {
     public static final android.os.Parcelable$Creator *;
   }

 -keepclassmembers public class org.springframework {
     public *;
 }

### apache http client for android
-dontwarn org.apache.commons.**
-keep class org.apache.http.** { *; }
-dontwarn org.apache.http.**

# http://stackoverflow.com/questions/16474904/proguard-with-android-java-lang-nosuchmethoderror-android-util-xml-asattribute
-keep class org.xmlpull.v1.** { *; }
```
