### ISSUE TITLE
rx.exceptions.OnErrorNotImplementedException

### ISSUE THREAD

**Issue by rajajawahar** [mcharmas/Android-ReactiveLocation#155]
FATAL EXCEPTION: main
                                                                                            Process: pl.charmas.android.reactivelocation.sample, PID: 30333
                                                                                            rx.exceptions.OnErrorNotImplementedException
                                                                                                at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
                                                                                                at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
                                                                                                at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
                                                                                                at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:152)
                                                                                                at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
                                                                                                at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:216)
                                                                                                at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
                                                                                                at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:398)
                                                                                                at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:358)
                                                                                                at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:849)
                                                                                                at pl.charmas.android.reactivelocation.observables.PendingResultObservable$1.onResult(PendingResultObservable.java:25)
                                                                                                at com.google.android.gms.internal.zzpo$zza.zzb(Unknown Source)
                                                                                                at com.google.android.gms.internal.zzpo$zza.handleMessage(Unknown Source)
                                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                at android.os.Looper.loop(Looper.java:148)
                                                                                                at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                                                                                             Caused by: java.lang.IllegalStateException
                                                                                                at com.google.android.gms.common.internal.zzab.zzbn(Unknown Source)
                                                                                                at com.google.android.gms.common.data.zzc.zzfq(Unknown Source)
                                                                                                at com.google.android.gms.common.data.zzc.<init>(Unknown Source)
                                                                                                at com.google.android.gms.location.places.internal.zzt.<init>(Unknown Source)
                                                                                                at com.google.android.gms.location.places.internal.zzn.<init>(Unknown Source)
                                                                                                at com.google.android.gms.location.places.PlaceLikelihoodBuffer.get(Unknown Source)
                                                                                                at pl.charmas.android.reactivelocation.sample.PlacesActivity$2.call(PlacesActivity.java:68)
                                                                                                at pl.charmas.android.reactivelocation.sample.PlacesActivity$2.call(PlacesActivity.java:65)
                                                                                                at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
                                                                                                at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
                                                                                                at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:398) 
                                                                                                at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:358) 
                                                                                                at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:849) 
                                                                                                at pl.charmas.android.reactivelocation.observables.PendingResultObservable$1.onResult(PendingResultObservable.java:25) 
                                                                                                at com.google.android.gms.internal.zzpo$zza.zzb(Unknown Source) 
                                                                                                at com.google.android.gms.internal.zzpo$zza.handleMessage(Unknown Source) 
                                                                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                                at android.os.Looper.loop(Looper.java:148) 
                                                                                                at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by arashsammak** [comment]
I have the same problem!

**Comment by arashsammak** [comment]
SLOVED :

```
@Override
    public void call(final Subscriber<? super T> subscriber) {
        result.setResultCallback(new ResultCallback<T>() {
            @Override
            public void onResult(@NonNull T t) {
                subscriber.onNext(t);
                complete = true;
                subscriber.onCompleted();
            }
        });
        subscriber.add(Subscriptions.create(new Action0() {
            @Override
            public void call() {
                if (!complete) {
                    result.cancel();
                }
            }
        }));
    }
```

need @NotNull before T t

**Comment by Lir10** [comment]
Same here

**Comment by JChudasama** [comment]
I also have same problem.

Any help will be appreciated !

**Comment by porkyhead** [comment]
Me too - I would be really nice to have this fixed!

**Comment by mladenbabic** [comment]
I have the same problem. Please provide a fix or patch so that we can continue to use this lib. 
Tnx

**Comment by JChudasama** [comment]
Anyone here to help ? Causing the problem quite frequent now :(

**Comment by mcharmas** [comment]
This is not library error. Please read about handling errors in RxJava.

You have to pass error callback (second parameter) to subscribe method and handle error.
