### ISSUE TITLE
[BUG] IllegalArgumentException

### ISSUE THREAD

**Issue by Lir10** [mcharmas/Android-ReactiveLocation#157]
This is the stack trace : 

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.handleStopService(ActivityThread.java:3363)
  at android.app.ActivityThread.access$2300(ActivityThread.java:177)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1552)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:145)
  at android.app.ActivityThread.main(ActivityThread.java:5951)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Caused by: java.lang.IllegalArgumentException: 
  at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:822)
  at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:2038)
  at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:528)
  at pl.charmas.android.reactivelocation.observables.activity.ActivityUpdatesObservable.onUnsubscribed(ActivityUpdatesObservable.java:50)
  at pl.charmas.android.reactivelocation.observables.BaseObservable$1.call(BaseObservable.java:44)
  at rx.subscriptions.BooleanSubscription.unsubscribe(BooleanSubscription.java:71)
  at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:136)
  at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:125)
  at rx.Subscriber.unsubscribe(Subscriber.java:98)
  at com.mynavy.myapp.myservice.onDestroy(myservice.java:299)
  at android.app.ActivityThread.handleStopService(ActivityThread.java:3346)
```

Im getting this from couple of users in my app when the service is destroyed on unsubscribe, Any ideas?

**Comment by mrArtCore** [comment]
Hi, how about more code ? ))) 
What is  `activitySubscription` ??  is it stored in service ?

**Comment by Lir10** [comment]
@mrArtCore  Hi , yeah 
This is what im doing `onCreate()` in the service : 
```
@Override
public void onCreate() {
    locationProvider = new ReactiveLocationProvider(this);
    activitySubscription = locationProvider.getDetectedActivity(60 *1000) 

                .subscribe(new Action1<ActivityRecognitionResult>() {
                    @Override
                    public void call(ActivityRecognitionResult detectedActivity) {
                                // Some code
                   }, new Action1<Throwable>() {
                    @Override
                    public void call(Throwable onError) {
                        onError.printStackTrace();
                }
         });
}
```
and `onDestroy()` :

@Override
    public void onDestroy(){
        if(!activitySubscription.isUnsubscribed()) {
            activitySubscription.unsubscribe();
        }
}

**Comment by Lir10** [comment]
@mrArtCore @mcharmas Any ideas what is this cause to this problem ? i'm getting this alot lately :/

**Comment by Lir10** [comment]
The problem lies here :  https://github.com/mcharmas/Android-ReactiveLocation/blob/master/android-reactive-location/src/main/java/pl/charmas/android/reactivelocation/observables/activity/ActivityUpdatesObservable.java

in `onUnsubscribed()`

replace this :
 ```
@Override
    protected void onUnsubscribed(GoogleApiClient apiClient) {
        if (apiClient.isConnected()) {
            ActivityRecognition.ActivityRecognitionApi.removeActivityUpdates(apiClient, getReceiverPendingIntent());
        }
        context.unregisterReceiver(receiver);
        receiver = null;
}
```

with this 

 ```
@Override
    protected void onUnsubscribed(GoogleApiClient apiClient) {
        if (apiClient.isConnected()) {
            ActivityRecognition.ActivityRecognitionApi.removeActivityUpdates(apiClient, getReceiverPendingIntent());
        }
        if (receiver != null) {
               context.unregisterReceiver(receiver);
               receiver = null;
       }
}
```

and we should add a try/catch on our service/activity `onDestory()` like this 

@Override
    public void onDestroy(){
        if(!activitySubscription.isUnsubscribed()) {
            try  {
                     activitySubscription.unsubscribe();
             }
             catch (IllegalArgumentException e) {
                e.printStackTrace();
             }
        }
}

**Comment by mcharmas** [comment]
I'll take a look at it later today and fix it.

I am just wondering when ```receiver``` is ```null``` in this context.

**Comment by Lir10** [comment]
@mcharmas Hi , I guess `onUnsubscribed()` gets called multiple times for no reason
