### ISSUE TITLE
[Bug] Mock Location Activity Sample

### ISSUE THREAD

**Issue by dineshmm23** [mcharmas/Android-ReactiveLocation#199]
> java.lang.NullPointerException: Attempt to invoke interface method 'void io.reactivex.disposables.Disposable.dispose()' on a null object reference
>         at pl.charmas.android.reactivelocation2.sample.MockLocationsActivity.setMockMode(MockLocationsActivity.java:141)
>         at pl.charmas.android.reactivelocation2.sample.MockLocationsActivity.access$000(MockLocationsActivity.java:36)
>         at pl.charmas.android.reactivelocation2.sample.MockLocationsActivity$1.onCheckedChanged(MockLocationsActivity.java:77)
>         at android.widget.CompoundButton.setChecked(CompoundButton.java:154)
>         at android.widget.ToggleButton.setChecked(ToggleButton.java:73)
>         at android.widget.CompoundButton.toggle(CompoundButton.java:113)
>         at android.widget.CompoundButton.performClick(CompoundButton.java:118)
>         at android.view.View$PerformClick.run(View.java:20260)
>         at android.os.Handler.handleCallback(Handler.java:815)
>         at android.os.Handler.dispatchMessage(Handler.java:104)
>         at android.os.Looper.loop(Looper.java:194)
>         at android.app.ActivityThread.main(ActivityThread.java:5624)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at java.lang.reflect.Method.invoke(Method.java:372)
>         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

**Comment by dineshmm23** [comment]
This happened on turning off mock location
