### ISSUE TITLE
Error while detecting location

### ISSUE THREAD

**Issue by kalyandechiraju** [mcharmas/Android-ReactiveLocation#200]
Got the below error log when trying to detect the location on Android Marshmallow

```
E/null: java.lang.RuntimeException: Wrong API response
        at pl.charmas.android.reactivelocation2.observables.geocode.FallbackReverseGeocodeObservable.alternativeReverseGeocodeQuery(FallbackReverseGeocodeObservable.java:86)
        at pl.charmas.android.reactivelocation2.observables.geocode.FallbackReverseGeocodeObservable.subscribe(FallbackReverseGeocodeObservable.java:39)
        at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
```

**Comment by dineshmm23** [comment]
io.reactivex.exceptions.OnErrorNotImplementedException: Wrong API response
     at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
     at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
     at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
     at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.checkTerminated(ObservableObserveOn.java:276)
     at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:172)
     at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
     at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
     at android.os.Handler.handleCallback(Handler.java:790)
     at android.os.Handler.dispatchMessage(Handler.java:99)
     at android.os.Looper.loop(Looper.java:164)
     at android.app.ActivityThread.main(ActivityThread.java:6626)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
	 
Caused by: java.lang.RuntimeException: Wrong API response
     at pl.charmas.android.reactivelocation2.observables.geocode.FallbackReverseGeocodeObservable.alternativeReverseGeocodeQuery(FallbackReverseGeocodeObservable.java:86)
     at pl.charmas.android.reactivelocation2.observables.geocode.FallbackReverseGeocodeObservable.subscribe(FallbackReverseGeocodeObservable.java:39)
     at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
     at io.reactivex.Observable.subscribe(Observable.java:12051)
     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:579)
     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
     at java.lang.Thread.run(Thread.java:764)


I'm too getting this error..

Found that is response error handler  ..but i don't know how to handle ...
`// Other non-OK responses status
            if (!"OK".equalsIgnoreCase(jsonRootObject.getString("status"))) {
                throw new RuntimeException("Wrong API response");
}`


> Can i help me how to handle it

**Comment by rohithThammaiah** [comment]
+1
