### ISSUE TITLE
gms DeadObjectException

### ISSUE THREAD

**Issue by sytolk** [mcharmas/Android-ReactiveLocation#22]
this Exception is with version 0.2 and play service v. 5.x.x
I have read this:
http://stackoverflow.com/questions/24288685/deadobjectexception-in-gmslocationclient-android

d.a.d: android.os.DeadObjectException
   at d.c.a.b(SafeSubscriber.java:184)
   at d.c.a.a(SafeSubscriber.java:94)
   at d.d.a$1.a(OperatorFilter.java:47)
   at c.a.a.a.a.b.a(BaseLocationObservable.java:69)
   at com.google.android.gms.internal.il.a(Unknown Source)
   at com.google.android.gms.internal.iq.a(Unknown Source)
   at com.google.android.gms.internal.iq.a(Unknown Source)
   at com.google.android.gms.internal.ip.a(Unknown Source)
   at com.google.android.gms.internal.ip.a(Unknown Source)
   at com.google.android.gms.internal.ik.b(Unknown Source)
   at com.google.android.gms.internal.ij.handleMessage(Unknown Source)
   at android.os.Handler.dispatchMessage(Handler.java:99)
   at android.os.Looper.loop(Looper.java:137)
   at android.app.ActivityThread.main(ActivityThread.java:4747)
   at java.lang.reflect.Method.invokeNative(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:511)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
   at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalStateException: android.os.DeadObjectException
   at com.google.android.gms.location.d.a(Unknown Source)
   at c.a.a.a.a.a.a.a(LocationUpdatesObservable.java:42)
   at c.a.a.a.a.a$1.a(BaseLocationObservable.java:42)
   at d.f.c.b(Subscriptions.java:63)
   at d.f.a.a(SubscriptionList.java:86)
   at d.f.a.b(SubscriptionList.java:76)
   at d.e.b(Subscriber.java:66)
   at d.c.a.b(SafeSubscriber.java:177)
   ... 18 more
Caused by: android.os.DeadObjectException
   at android.os.BinderProxy.transact(Native Method)
   at com.google.android.gms.internal.lw.a(Unknown Source)
   at com.google.android.gms.internal.lx.a(Unknown Source)
   at com.google.android.gms.internal.ma.a(Unknown Source)
   ... 26 more
java.lang.IllegalStateException: android.os.DeadObjectException
   at com.google.android.gms.location.d.a(Unknown Source)
   at c.a.a.a.a.a.a.a(LocationUpdatesObservable.java:42)
   at c.a.a.a.a.a$1.a(BaseLocationObservable.java:42)
   at d.f.c.b(Subscriptions.java:63)
   at d.f.a.a(SubscriptionList.java:86)
   at d.f.a.b(SubscriptionList.java:76)
   at d.e.b(Subscriber.java:66)
   at d.c.a.b(SafeSubscriber.java:177)
   at d.c.a.a(SafeSubscriber.java:94)
   at d.d.a$1.a(OperatorFilter.java:47)
   at c.a.a.a.a.b.a(BaseLocationObservable.java:69)
   at com.google.android.gms.internal.il.a(Unknown Source)
   at com.google.android.gms.internal.iq.a(Unknown Source)
   at com.google.android.gms.internal.iq.a(Unknown Source)
   at com.google.android.gms.internal.ip.a(Unknown Source)
   at com.google.android.gms.internal.ip.a(Unknown Source)
   at com.google.android.gms.internal.ik.b(Unknown Source)
   at com.google.android.gms.internal.ij.handleMessage(Unknown Source)
   at android.os.Handler.dispatchMessage(Handler.java:99)
   at android.os.Looper.loop(Looper.java:137)
   at android.app.ActivityThread.main(ActivityThread.java:4747)
   at java.lang.reflect.Method.invokeNative(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:511)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
   at dalvik.system.NativeStart.main(Native Method)
Caused by: android.os.DeadObjectException
   at android.os.BinderProxy.transact(Native Method)
   at com.google.android.gms.internal.lw.a(Unknown Source)
   at com.google.android.gms.internal.lx.a(Unknown Source)
   at com.google.android.gms.internal.ma.a(Unknown Source)
   ... 26 more
android.os.DeadObjectException
   at android.os.BinderProxy.transact(Native Method)
   at com.google.android.gms.internal.lw.a(Unknown Source)
   at com.google.android.gms.internal.lx.a(Unknown Source)
   at com.google.android.gms.internal.ma.a(Unknown Source)
   at com.google.android.gms.location.d.a(Unknown Source)
   at c.a.a.a.a.a.a.a(LocationUpdatesObservable.java:42)
   at c.a.a.a.a.a$1.a(BaseLocationObservable.java:42)
   at d.f.c.b(Subscriptions.java:63)
   at d.f.a.a(SubscriptionList.java:86)
   at d.f.a.b(SubscriptionList.java:76)
   at d.e.b(Subscriber.java:66)
   at d.c.a.b(SafeSubscriber.java:177)
   at d.c.a.a(SafeSubscriber.java:94)
   at d.d.a$1.a(OperatorFilter.java:47)
   at c.a.a.a.a.b.a(BaseLocationObservable.java:69)
   at com.google.android.gms.internal.il.a(Unknown Source)
   at com.google.android.gms.internal.iq.a(Unknown Source)
   at com.google.android.gms.internal.iq.a(Unknown Source)
   at com.google.android.gms.internal.ip.a(Unknown Source)
   at com.google.android.gms.internal.ip.a(Unknown Source)
   at com.google.android.gms.internal.ik.b(Unknown Source)
   at com.google.android.gms.internal.ij.handleMessage(Unknown Source)
   at android.os.Handler.dispatchMessage(Handler.java:99)
   at android.os.Looper.loop(Looper.java:137)
   at android.app.ActivityThread.main(ActivityThread.java:4747)
   at java.lang.reflect.Method.invokeNative(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:511)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
   at dalvik.system.NativeStart.main(Native Method)

**Comment by mcharmas** [comment]
Hmm, so reading the SO answer there is not much we can do in the library unfortunatelly. If you have this kind of issues you need to implement onError handler properly to handle such situations. Do you have different opinion?

**Comment by sytolk** [comment]
I have onError but this Exception is not handled the application is crashed this is log from ACRA. I`m not familiar with rxjava Exception handling. I need to try catch this exception to avoid application crash. Is this code wrong ?

```java
subscription = locationProvider.getUpdatedLocation(request)
                .filter(new Func1<Location, Boolean>() {
                    @Override
                    public Boolean call(Location location) {
                        return location.getAccuracy() < SUFFICIENT_ACCURACY;
                    }
                })  
                .subscribe(new Action1<Location>() {
                    @Override
                    public void call(Location location) {
                        doObtainedLocation(location);
                    }
                }, new Action1<Throwable>() {
                    @Override
                    public void call(Throwable onError) {
                        onError.printStackTrace();
                    }
                });
```

**Comment by sytolk** [comment]
b) Catch the IllegalStateException (and not the DeadObjectException)
http://docs.oracle.com/javase/7/docs/api/java/lang/IllegalStateException.html
public class IllegalStateException extends RuntimeException

maybe rxjava not catch RuntimeException

**Comment by cyrixmorten** [comment]
Not entirely the same, but did some tests with and AVD without Google Play Services and despite having implemented .doOnError:

       locationSubscription = locationProvider.getUpdatedLocation(request)
                .doOnError(new Action1<Throwable>() {
                    @Override
                    public void call(Throwable throwable) {
                        if (BuildConfig.DEBUG) {
                            String message = "Error on location update: " + throwable.getMessage();
                            Log.e(TAG, message, throwable);
                            Crashlytics.logException(throwable);
                        }
                    }
                }) 

I was getting: `rx.exceptions.OnErrorNotImplementedException: Error connecting to GoogleApiClient.`

Now extended it with .onErrorReturn which seems to handle the exception effectively avoiding OnErrorNotImplementedException.

        locationSubscription = locationProvider.getUpdatedLocation(request)
                .doOnError(new Action1<Throwable>() {
                    @Override
                    public void call(Throwable throwable) {
                        if (BuildConfig.DEBUG) {
                            String message = "Error on location update: " + throwable.getMessage();
                            Log.e(TAG, message, throwable);
                            Crashlytics.logException(throwable);
                        }
                    }
                })
                .onErrorReturn(new Func1<Throwable, Location>() {
                    @Override
                    public Location call(Throwable throwable) {
                        return null;
                    }
                })

**Comment by sytolk** [comment]
Thanks @cyrixmorten but try to write  .subscribe(..) before doOnError().onErrorReturn()
subscribe return Subscription object there is not doOnError and onErrorReturn methods in this object.
If the error will be handled if subscribe() is after doOnError and onErrorReturn ? and why subscribe have parameter OnError ?

**Comment by cyrixmorten** [comment]
Sorry I am not completely following. 

Maybe I should post the complete code, was just missing the subscribe part:

        locationSubscription = locationProvider.getUpdatedLocation(request)
                .doOnError(new Action1<Throwable>() {
                    @Override
                    public void call(Throwable throwable) {
                        if (BuildConfig.DEBUG) {
                            String message = "Error on location update: " + throwable.getMessage();
                            Log.e(TAG, message, throwable);
                            Crashlytics.logException(throwable);
                        }
                    }
                })
                .onErrorReturn(new Func1<Throwable, Location>() {
                    @Override
                    public Location call(Throwable throwable) {
                        return null;
                    }
                })
                .subscribe(new Action1<Location>() {
                    @Override
                    public void call(Location location) {

                        if (location == null)
                            return;

                        if (localData != null && localData.isGuardLoggedIn()) {
                            localData.setLastKnownLocation(location);
                            storeLocationAsJSON(location);
                            updateUIIfDistanceThresholdReached(location);
                            uploadIfTimeThresholdReached(location);
                        } else {
                            stopSelf();
                        }
                    }
                });

I cannot see how changing the order of .subscribe() .doOnError() and/or .onErrorReturn() should make a difference

**Comment by sytolk** [comment]
I don`t know.. but why its have parameter 3 onError on subscribe() maybe its the same like doOnError() but why exist? :)
Ok I will test this.
