### ISSUE TITLE
Error connecting to GoogleApiClient

### ISSUE THREAD

**Issue by nologinatgit** [mcharmas/Android-ReactiveLocation#45]
I've tried to use the library but when I started the location update subscription with this code:

I get these errors:

 rx.exceptions.OnErrorNotImplementedException: Error connecting to GoogleApiClient.
            at rx.Observable$36.onError(Observable.java:8420)
            at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:128)
            at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:97)
            at pl.charmas.android.reactivelocation.observables.BaseObservable$ApiClientConnectionCallbacks.onConnectionFailed(BaseObservable.java:107)
            at com.google.android.gms.common.internal.zzj.zzj(Unknown Source)
            at com.google.android.gms.common.api.zze.zzf(Unknown Source)
            at com.google.android.gms.common.api.zze.zzkP(Unknown Source)
            at com.google.android.gms.common.api.zze.zzf(Unknown Source)
            at com.google.android.gms.common.api.zze$zzc.zza(Unknown Source)
            at com.google.android.gms.common.internal.zzi$zzb.handleMessage(Unknown Source)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:130)
            at android.app.ActivityThread.main(ActivityThread.java:3687)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:507)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: pl.charmas.android.reactivelocation.observables.GoogleAPIConnectionException: Error connecting to GoogleApiClient.
            at pl.charmas.android.reactivelocation.observables.BaseObservable$ApiClientConnectionCallbacks.onConnectionFailed(BaseObservable.java:107)
            at com.google.android.gms.common.internal.zzj.zzj(Unknown Source)
            at com.google.android.gms.common.api.zze.zzf(Unknown Source)
            at com.google.android.gms.common.api.zze.zzkP(Unknown Source)
            at com.google.android.gms.common.api.zze.zzf(Unknown Source)
            at com.google.android.gms.common.api.zze$zzc.zza(Unknown Source)
            at com.google.android.gms.common.internal.zzi$zzb.handleMessage(Unknown Source)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:130)
            at android.app.ActivityThread.main(ActivityThread.java:3687)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:507)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
            at dalvik.system.NativeStart.main(Native Method)

What should I set?

**Comment by sytolk** [comment]
Do you have google play service installed on emulator or device?

**Comment by mcharmas** [comment]
@nologinatgit the basic idea of RxJava is that you can deliver onError callback to subscribe method and catch this exception. This exception means that your app can't connect to google play services. This can happen due to multiple reasons, one of which is that GMS is not installed on the device.

**Comment by sytolk** [comment]
I see that its have GMS installed form package com.google.android.gms.common.internal
```
pl.charmas.android.reactivelocation.observables.BaseObservable$ApiClientConnectionCallbacks.onConnectionFailed(BaseObservable.java:107)
at com.google.android.gms.common.internal.zzj.zzj(Unknown Source)
```
@nologinatgit do you have GMS with Proguard ? like this issue:
https://github.com/mcharmas/Android-ReactiveLocation/issues/22

**Comment by mcharmas** [comment]
@sytolk this looks like local dependency. The part of GMS that is delivered with application. There should be a second part which is probably not installed or unavailable.

**Comment by nologinatgit** [comment]
How can I see which part is unavailable?

**Comment by nologinatgit** [comment]
@sytolk I don't use Proguard.

**Comment by mcharmas** [comment]
I think you should read the docs about google play services. This should help. Testing it on regular emulator or device without google play will not work. You can try emulator with google apis or regular device. The issue is not connected with library.

**Comment by IgorGanapolsky** [comment]
When I comment out ReactiveLocationProvider code, and run it on the emulator, then the app doesn't crash.  Otherwise, it always crashes.

**Comment by abhaysood** [comment]
How can we handle this error more elegantly?

**Comment by mcharmas** [comment]
@abhaysood You have to implement onError callback (second parameter to subscribe method).
