### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by mynavy** [mcharmas/Android-ReactiveLocation#60]
on htc 1 with android 4.1.1 i keep getting crashes

logcat
```javascript

 Could not find class 'android.app.AppOpsManager', referenced from method com.google.android.gms.common.GooglePlayServicesUtil.zza
07-23 17:03:59.747  26391-26391/ E/AndroidRuntime﹕ FATAL EXCEPTION: main
    rx.exceptions.OnErrorNotImplementedException: Error connecting to GoogleApiClient.
            at rx.Observable$30.onError(Observable.java:7334)
            at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:154)
            at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:111)
            at pl.charmas.android.reactivelocation.observables.BaseObservable$ApiClientConnectionCallbacks.onConnectionFailed(BaseObservable.java:107)
            at com.google.android.gms.common.internal.zzj.zzh(Unknown Source)
            at com.google.android.gms.common.api.zze.zzd(Unknown Source)
            at com.google.android.gms.common.api.zze.zza(Unknown Source)
            at com.google.android.gms.common.api.zze$1.run(Unknown Source)
            at android.os.Handler.handleCallback(Handler.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:155)
            at android.app.ActivityThread.main(ActivityThread.java:5454)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: pl.charmas.android.reactivelocation.observables.GoogleAPIConnectionException: Error connecting to GoogleApiClient.
            at pl.charmas.android.reactivelocation.observables.BaseObservable$ApiClientConnectionCallbacks.onConnectionFailed(BaseObservable.java:107)
            at com.google.android.gms.common.internal.zzj.zzh(Unknown Source)
            at com.google.android.gms.common.api.zze.zzd(Unknown Source)
            at com.google.android.gms.common.api.zze.zza(Unknown Source)
            at com.google.android.gms.common.api.zze$1.run(Unknown Source)
            at android.os.Handler.handleCallback(Handler.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:155)
            at android.app.ActivityThread.main(ActivityThread.java:5454)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by mynavy** [comment]
Figured out that Google location was off 

is ther any way to check catch this error ?

**Comment by mcharmas** [comment]
Yes,
just use standard onError handler to subscribe method. Check out Observable.subscribe() method doc's. There is an option to pass error handler as second param.
