### ISSUE TITLE
in sample-app: Internal data leak within a DataBuffer object detected!  Be sure to explicitly call release() on all DataBuffer extending objects when you are done with them. (AutocompletePredictionBuffer{status=Status{statusCode=SUCCESS, resolution=null}})

### ISSUE THREAD

**Issue by Rainer-Lang** [mcharmas/Android-ReactiveLocation#68]
08-21 09:04:26.063    2556-2570/pl.charmas.android.reactivelocation.sample E/DataBuffer﹕ Internal data leak within a DataBuffer object detected!  Be sure to explicitly call release() on all DataBuffer extending objects when you are done with them. (AutocompletePredictionBuffer{status=Status{statusCode=SUCCESS, resolution=null}})

**Comment by mcharmas** [comment]
@Rainer-Lang could you elaborate more? Did where did it happen? Did you modify any code? Any way to reproduce it?

**Comment by Rainer-Lang** [comment]
I didn't modify anything.
I run the sample, type a few letters, switch apps - and after a few minutes I get the leak.
Sorry, I also tried to reproduce the leak - but it occurs after time...

**Comment by mcharmas** [comment]
@Rainer-Lang thanks for reporting. Found it! It was an error only in sample app. I was not using proper util observable that recycles DataBuffers after unsubscription.

More details in commit 9fe79035801e97ea7c48b1dc6a7cc4ae5e13a554.

**Comment by Rainer-Lang** [comment]
Great. Thanks for fixing so quick!

**Comment by Rainer-Lang** [comment]
Sorry: Also sample-app - buffer closed -> error

```
08-21 13:20:35.220  31594-31594/pl.charmas.android.reactivelocation.sample E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: pl.charmas.android.reactivelocation.sample, PID: 31594
    java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
            at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: rx.exceptions.OnErrorNotImplementedException: Buffer is closed.
            at rx.Observable$30.onError(Observable.java:7540)
            at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:154)
            at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:111)
            at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:137)
            at rx.android.app.OperatorConditionalBinding$1.onNext(OperatorConditionalBinding.java:79)
            at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:208)
            at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:170)
            at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.IllegalArgumentException: Buffer is closed.
            at com.google.android.gms.common.data.DataHolder.zzg(Unknown Source)
            at com.google.android.gms.common.data.DataHolder.zzi(Unknown Source)
            at com.google.android.gms.common.data.zzc.zzbX(Unknown Source)
            at com.google.android.gms.location.places.internal.zzt.zzB(Unknown Source)
            at com.google.android.gms.location.places.internal.zzb.getDescription(Unknown Source)
            at pl.charmas.android.reactivelocation.sample.PlacesActivity$8.call(PlacesActivity.java:127)
            at pl.charmas.android.reactivelocation.sample.PlacesActivity$8.call(PlacesActivity.java:120)
            at rx.Observable$30.onNext(Observable.java:7545)
            at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:130)
            at rx.android.app.OperatorConditionalBinding$1.onNext(OperatorConditionalBinding.java:79)
            at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:208)
            at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:170)
            at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by mcharmas** [comment]
Yep, I've definitely screwed up this one...

I'll fix it on Monday. Have a nice weekend!

**Comment by Rainer-Lang** [comment]
Nevermind. :-)
Have also a nice weekend.

**Comment by Rainer-Lang** [comment]
Any news? :-)

**Comment by macr00** [comment]
Firstly, thanks for this library - looks very useful!
Unfortunately, I've also encountered the 'Buffer is closed' error... any suggestions in fixing this?

**Comment by mcharmas** [comment]
Hi guys,
sorry that it took so long. I've been looking how DataBuffers work in GMS and I am afraid that ```DataBufferObservable``` is broken. The bad news is that I have no idea how to fix it and how to automatically recycle DataBuffers after consumption.

For now a workaround would be to not use ```DataBufferObservable``` and close DataBuffers manually after consumption in OnSubscribe callback.

**Comment by mcharmas** [comment]
I've updated samples with this commit: 103c2438577a4681c79782d4e263352ab42f4df3

**Comment by Rainer-Lang** [comment]
Thanks. I will look into the sample later. 
Thanks for the great lib!

**Comment by macr00** [comment]
Thanks again! Nice solution :)

**Comment by schwiz** [comment]
Could the issue be you are calling the 'add' after you are subscribing? Perhaps you should call subscriber.add and then subscribe on the buffer observable.

**Comment by schwiz** [comment]
Could the issue with DataBufferObservable be that you are adding the unsubscribe action after subscribing to the observable?

**Comment by JagadishSivakumar** [comment]
The Buffer is not to be closed but the connection instead. This is commonly a result of a callback , a connection was established.

While using Google Maps API i saw the same logcat output.

Add 
`GoogleApiClient.disconnect()
`
at the end of activity/fragment life cycle
