### ISSUE TITLE
Possible workaround for "Service not Available" in ReverseGeocodeObservable

### ISSUE THREAD

**Issue by zoltanf** [mcharmas/Android-ReactiveLocation#86]
There are lot of devices, that for some reason (my suspition is after upgrade to the google play services but before restart) give this exception. It is most probably possible to use an alternative way to get the info directly from the Google's APIs (via http query) in case when this specific exception happens. 

    LocationRepository::getReverseGeocodeObservable
    java.io.IOException: Service not Available
        at android.location.Geocoder.getFromLocation(Geocoder.java:136)
        at pl.charmas.android.reactivelocation.observables.geocode.ReverseGeocodeObservable.call(ReverseGeocodeObservable.java:34)
        at pl.charmas.android.reactivelocation.observables.geocode.ReverseGeocodeObservable.call(ReverseGeocodeObservable.java:13)
        at rx.Observable.unsafeSubscribe(Observable.java:7710)
        at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
        at java.util.concurrent.FutureTask.run(FutureTask.java:137)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:150)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
        at java.lang.Thread.run(Thread.java:856)

Thank you for this lib.

**Comment by cyrixmorten** [comment]
Hi

I have answered an SO question that matches your idea:
http://stackoverflow.com/questions/19059894/google-geocoder-service-is-unavaliable-coordinates-to-address/19061688#19061688

I am sure that you are more than welcome to create a pull an add a similar
fallback to this library.

Best Regards

2015-11-13 10:42 GMT+01:00 zoltanf <notifications@github.com>:

**Comment by mcharmas** [comment]
@zoltanf that would be great feature but unfortunately not time to implement it on my side
PR would be welcome

**Comment by zoltanf** [comment]
OK, will prep a PR for this.

**Comment by zoltanf** [comment]
Will close this issue as the latest version properly handles this. Thank you.

**Comment by mehdok** [comment]
The error still exist in the last version.

**Comment by zoltanf** [comment]
@mehdok can you post a full stack trace?
There was a pull request that was merged addressing this problem, it should not happen in newer versions.

**Comment by mehdok** [comment]
@zoltanf ok, i saw your code and you addressed this issue correctly, but your code does not exist in the latest (**0.10@aar**) version :)

**Comment by zoltanf** [comment]
@mehdok So I finally took some time to check and looked at the 0.10 release aar and I can assure you that the fallback reverse geocode observable and the code that triggers the fallback is in there unchanged. I hope that clears it up. There could be some other situations (other kind of exceptions) that we are not handling but in case you have such example please post the full exception stack trace and we can try to handle it.

![image](https://cloud.githubusercontent.com/assets/1464667/22542804/ffbaaf1e-e92d-11e6-8046-564c2763ba23.png)
![image](https://cloud.githubusercontent.com/assets/1464667/22542820/0d93ad84-e92e-11e6-85f6-f820f52b0ef2.png)

**Comment by Mitutov** [comment]
`Caused by: java.io.IOException: grpc failed
                                                                                 at android.location.Geocoder.getFromLocation(Geocoder.java:136)
                                                                                 at pl.charmas.android.reactivelocation2.observables.geocode.ReverseGeocodeObservable.subscribe(ReverseGeocodeObservable.java:41)
                                                                                 at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
                                                                                 at io.reactivex.Observable.subscribe(Observable.java:10700)
                                                                                 at io.reactivex.internal.operators.observable.ObservableSubscribeOn$1.run(ObservableSubscribeOn.java:39)
                                                                                 at io.reactivex.Scheduler$1.run(Scheduler.java:138)
                                                                                 at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59)
                                                                                 at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
                                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                 at java.lang.Thread.run(Thread.java:818)`

**Comment by gone-phishing** [comment]
Facing the same problem, any updates?

**Comment by mehdok** [comment]
@gone-phishing It is fixed by now, just update the library to the latest version.

**Comment by Mitutov** [comment]
@mehdok 
I checked `ReverseGeocodeObservable.java` and saw that the "grpc failed" [error](https://stackoverflow.com/questions/45012289/java-io-ioexception-grpc-failed) has not been fixed at this time in the latest version (RxJava and RxJava2 branches).

Code now:
```
            if (e.getMessage().equalsIgnoreCase("Service not Available")) {
                Observable
                        .create(new FallbackReverseGeocodeObservable(locale, latitude, longitude, maxResults))
                        .subscribeOn(Schedulers.io())
                        .subscribe(subscriber);
            } else {
                subscriber.onError(e);
            }
```

Should be:
```
            if (e.getMessage().equalsIgnoreCase("Service not Available") || e.getMessage().equalsIgnoreCase("grpc failed")) {
                Observable
                        .create(new FallbackReverseGeocodeObservable(locale, latitude, longitude, maxResults))
                        .subscribeOn(Schedulers.io())
                        .subscribe(new ObservableEmitterWrapper<>(emitter));
            } else {
                emitter.onError(e);
            }
```

**Comment by mcharmas** [comment]
@Mitutov I'll fix it today with other issues and release new lib version. I am wondering if it is necessary to check message at all. Maybe in case of any error we should try the fallback option. What do you think?

**Comment by Mitutov** [comment]
@mcharmas 

> Maybe in case of any error we should try the fallback option. 

I think this is the best solution.

**Comment by mcharmas** [comment]
Fixed in: 5fa93a67e4d6c17bb9755ce838da772e7cb91b61

**Comment by Shahar2k5** [comment]
Sorry to bring that up again, but I keep getting the same error with the latest version.
using 

`
    compile 'com.google.android.gms:play-services-location:11.4.2'
    compile 'com.google.android.gms:play-services-places:11.4.2'
    compile "io.reactivex.rxjava2:rxjava:2.1.3"
    compile 'pl.charmas.android:android-reactive-location2:2.0@aar'
`
(also happens with 11.0.4 play-services)


`Fatal Exception: io.reactivex.exceptions.UndeliverableException: java.io.IOException: grpc failed
       at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:349)
       at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onError(ObservableCreate.java:74)
       at pl.charmas.android.reactivelocation2.observables.geocode.ReverseGeocodeObservable.subscribe(ReverseGeocodeObservable.java:54)
       at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
       at io.reactivex.Observable.subscribe(Observable.java:10903)
       at io.reactivex.internal.operators.observable.ObservableFilter.subscribeActual(ObservableFilter.java:30)
       at io.reactivex.Observable.subscribe(Observable.java:10903)
       at io.reactivex.internal.operators.observable.ObservableObserveOn.subscribeActual(ObservableObserveOn.java:45)
       at io.reactivex.Observable.subscribe(Observable.java:10903)
       at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
       at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.io.IOException: grpc failed
       at android.location.Geocoder.getFromLocation(Geocoder.java:136)
       at pl.charmas.android.reactivelocation2.observables.geocode.ReverseGeocodeObservable.subscribe(ReverseGeocodeObservable.java:41)
       at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
       at io.reactivex.Observable.subscribe(Observable.java:10903)
       at io.reactivex.internal.operators.observable.ObservableFilter.subscribeActual(ObservableFilter.java:30)
       at io.reactivex.Observable.subscribe(Observable.java:10903)
       at io.reactivex.internal.operators.observable.ObservableObserveOn.subscribeActual(ObservableObserveOn.java:45)
       at io.reactivex.Observable.subscribe(Observable.java:10903)
       at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
       at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)`

**Comment by Shahar2k5** [comment]
OK... might be related to this?
https://github.com/ReactiveX/RxJava/issues/5099
