### ISSUE TITLE
Crash when Play Services are not installed.

### ISSUE THREAD

**Issue by fabiocarballo** [mcharmas/Android-ReactiveLocation#91]
Fatal Exception: java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
       at android.os.Handler.handleCallback(Handler.java:730)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5473)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:806)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by rx.exceptions.OnErrorNotImplementedException
       at rx.Observable$27.onError(Observable.java:7923)
       at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:159)
       at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:191)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:162)
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
       at android.os.Handler.handleCallback(Handler.java:730)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5473)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:806)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by pl.charmas.android.reactivelocation.observables.GoogleAPIConnectionSuspendedException
       at pl.charmas.android.reactivelocation.observables.BaseObservable$ApiClientConnectionCallbacks.onConnectionSuspended(BaseObservable.java:102)
       at com.google.android.gms.common.internal.zzk.zzbB(Unknown Source)
       at com.google.android.gms.common.api.zzf.onConnectionSuspended(Unknown Source)
       at com.google.android.gms.common.api.zzi$2.onConnectionSuspended(Unknown Source)
       at com.google.android.gms.common.internal.zzj$zzb.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5473)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:806)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
       at dalvik.system.NativeStart.main(NativeStart.java)

Any idea on how to fix this? I'm having some crashes on our production app and we heavily depend on location :/

Thank you!

**Comment by cyrixmorten** [comment]
Did you add the second action parameter to your subscription?

Or, try to add onError to the observable?

**Comment by fabiocarballo** [comment]
Yup.. I'm implementing it!

**Comment by fabiocarballo** [comment]
I forgot to say but this is happening on the 0.8 release..

**Comment by fabiocarballo** [comment]
@cyrixmorten edit the title. I have found that the cause is that the users don't have play services installed.

Any known workaround on this?

**Comment by cyrixmorten** [comment]
I would suppose you have to verify whether play services are available before using this library: http://stackoverflow.com/questions/22493465/check-if-correct-google-play-service-available-unfortunately-application-has-s
